#


qac0:
	pdflatex memo59.tex
	bibtex memo59
	pdflatex memo59.tex
	@echo xdg-open memo59.pdf

#
qac:
	latex memo59.tex
	latex memo59.tex
	bibtex memo59
	latex memo59.tex
	latex memo59.tex
	dvipdfm memo59

# this works for PJT
pdf1:
	pdflatex teuben_shortspacing.tex

# according to ASP
pdf2:
	latex teuben_shortspacing.tex
	latex teuben_shortspacing.tex
	dvipdfm teuben_shortspacing.dvi

