#


#

# this works for PJT
pdf1:
	pdflatex teuben_shortspacing.tex

# according to ASP
pdf2:
	latex teuben_shortspacing.tex
	latex teuben_shortspacing.tex
	dvipdfm teuben_shortspacing.dvi

qac:
	latex memo-qac.tex
	latex memo-qac.tex
	bibtex memo-qac
	latex memo-qac.tex
	latex memo-qac.tex
	dvipdfm memo-qac
