

help:
	@echo no help

test:
	./mkgalcube run=model0 beam=0
	./mkgalcube run=model1 
	./mkgalcube run=model2 beam=0.5
	./mkgalcube run=model3 beam=0.5 vbeam=10
	./mkgalcube run=model4 beam=0.5 noise=0.001
	./mkgalcube run=model5 beam=0.5 noise=0.0001 nmode=1
